In [1]:
!nvidia-smi#查看GPU的个数类型，已占用内存大小，和总内存大小

Tue Jun 01 18:38:15 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 452.56       Driver Version: 452.56       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060   WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   40C    P8     5W /  N/A |    516MiB /  6144MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
from torch import nn

In [3]:
#查看可用GPU的数量
torch.cuda.device_count()

1

In [4]:
#默认时张量创建在CPU上
X=torch.tensor([1,2,3])
X.device

device(type='cpu')

In [15]:
#张量利用.cuda()将其放置GPU上
X=torch.rand(2,3).cuda()
X

tensor([[0.0891, 0.1328, 0.4259],
        [0.9778, 0.4468, 0.6225]], device='cuda:0')

In [17]:
Y=torch.ones(2,3).cuda()
X+Y

tensor([[1.0891, 1.1328, 1.4259],
        [1.9778, 1.4468, 1.6225]], device='cuda:0')

In [23]:
#神经网络放置在GPU上
Net=nn.Sequential(nn.Linear(3,1))
Net=Net.to(device=torch.device('cuda'))
Z=torch.tensor([100,200,300],device=torch.device('cuda'),dtype=torch.float32)
Net(Z)

tensor([-6.6692], device='cuda:0', grad_fn=<AddBackward0>)

In [24]:
Net[0].weight.data.device

device(type='cuda', index=0)

In [ ]:
'''
总结：使用GPU前
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
然后在声明计算的张量和网络的时候在device参数上加上device=device
'''
